-- 구매자
-- 이름, 나이, 성별, 주소, 핸드폰
CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
   ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
   BUYER_NAME VARCHAR2(255) NOT NULL,
   BUYER_AGE NUMBER,
   BUYER_GENDER CHAR(10) CHECK (BUYER_GENDER IN ('남', '여')),
   BUYER_ADDRESS VARCHAR2(255),
   BUYER_PHONE VARCHAR2(255)
);

-- 상품
-- 브랜드, 이름, 가격, 재고
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_BRAND VARCHAR2(255) NOT NULL,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER,
   PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 주문 
-- 주문 상태, 주문 일자, 주문 완료 일자
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   ORDER_STATUS VARCHAR2(255) DEFAULT '배송중',
   ORDER_START_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   ORDER_END_DATE TIMESTAMP,
   BUYER_ID NUMBER,
   PRODUCT_ID NUMBER,
   CONSTRAINT FK_ORDER_BUYER FOREIGN KEY(BUYER_ID)
   REFERENCES TBL_BUYER(ID),
   CONSTRAINT FK_OUDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);

-- 이름, 나이, 성별, 주소, 핸드폰
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '짱구', 40, '남', '서울시 강남구', '010-3344-1234');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '유리', 20, '여', '서울시 종로구', '010-7848-5656');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '맹구', 35, '남', '서울시 노원구', '010-1313-7854');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '철수', 30, '남', '서울시 용산구', '010-5533-7711');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '훈이', 20, '남', '경기도 남양주시', '010-1234-5678');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '수지', 40, '여', '서울시 강북구', '010-4542-8753');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '봉미선', 50, '여', '서울시 강북구', '010-3456-7575');
INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '이태희', 20, '여', '서울시 스카이캐슬', '010-7345-1578');


-- 상품
-- 브랜드, 이름, 가격, 재고
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '뉴발란스', '브리즈 신발', 139000, 500);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '아디다스', '후드집업', 119000, 250);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '아크테릭스', '후드티', 290000, 100);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '로라로라', '반팔티셔츠', 38700, 600);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '엠엘비', '볼캡', 49000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '무신사', '스웨이드 가디건', 95890, 170);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '스웨이드', '청바지', 57600, 310);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '스파오', '반팔티셔츠', 25900, 120);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '아이더', '캐시미어 자켓', 618420, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '스탠리', '텀블러', 62000, 550);


-- 오더
-- 주문 상태, 주문 일자, 주문 완료 일자
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 1, 7);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 2, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 3, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 3, 5);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 4, 1);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 4, 7);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 4, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 4, 2);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 5, 1);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 5, 7);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 5, 9);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 5, 10);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 6, 10);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 8);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 1);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 5);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 4);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 6);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 7, 8);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 8, 1);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 8, 2);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 8, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 2, 5);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 2, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 5, 4);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 3, 3);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 3, 8);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 1, 10);
INSERT INTO TBL_ORDER(ID, BUYER_ID, PRODUCT_ID)
VALUES(SEQ_ORDER.NEXTVAL, 3, 10);

SELECT *
FROM TBL_ORDER;
























