-- 게시판 최근글 정렬
SELECT TP.ID, TP.POST_TITLE, TU.USER_EMAIL
FROM TBL_POST TP
JOIN TBL_USER TU
ON TP.USER_ID = TU.ID
ORDER BY ID DESC;

-- 댓글을 단 사용자
SELECT TR.REPLY_CONTENT, TU.USER_EMAIL
FROM TBL_REPLY TR
JOIN TBL_USER TU
ON TR.USER_ID = TU.ID
WHERE REPLY_CONTENT LIKE '%한민%';

/*
 * SQL의 실행 순서
 * 
 * FROM > JOIN > ON > WHERE > GROUP BY > HAVING > SELECT > ORDER BY
 * 
 * */

-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT TBU.*, TBP.PRODUCT_NAME
FROM (
   SELECT *
   FROM TBL_ORDER TBO
   WHERE PRODUCT_ID = (
      SELECT PRODUCT_ID
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
      HAVING COUNT(PRODUCT_ID) = (
         SELECT MAX(COUNT(PRODUCT_ID))
         FROM TBL_ORDER
         GROUP BY PRODUCT_ID
      )
   )
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;



-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
   SELECT PRODUCT_ID
   FROM TBL_ORDER
   GROUP BY PRODUCT_ID
   HAVING COUNT(PRODUCT_ID) = (
      SELECT MAX(COUNT(PRODUCT_ID))
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
   )
);

-- 1) 상품 이름과 총 판매 매출 조회
SELECT 
	PRODUCT_NAME AS "상품명",
	COUNT(PRODUCT_ID) * PRODUCT_PRICE AS "매출"
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE;


-- 2) 상품을 구매한 20~30대 구매자의 수 조회
SELECT COUNT(BUYER_AGE) || '건' AS "20~30대 구매자의 수"
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE BUYER_AGE >= 20
	AND BUYER_AGE < 40;
--GROUP BY BUYER_AGE;

-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회
SELECT BUYER_NAME AS "뉴발란스를 구매한 20대의 이름"
FROM(
	SELECT *
	FROM TBL_ORDER TBO
	JOIN TBL_BUYER TBB 
	ON TBO.BUYER_ID = TBB.ID
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	WHERE PRODUCT_BRAND LIKE '뉴발란스'
)
WHERE BUYER_AGE >= 20
	AND BUYER_AGE < 30;


--4) 여성의 나이대별 평균 지출 금액 조회

SELECT BUYER_AGE || '대' AS "여성의 나이대", ROUND(AVG(PRODUCT_PRICE)) || '원' AS "평균 지출 금액"
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBR
ON TBO.PRODUCT_ID = TBR.ID
WHERE BUYER_GENDER = '여'
GROUP BY BUYER_AGE
ORDER BY BUYER_AGE;

--SELECT *
--FROM TBL_PRODUCT;

--5) 쇼핑몰의 총 판매 액수 조회
SELECT SUM(PRODUCT_PRICE) || '원' AS "쇼핑몰 총 판매 금액"
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBR
ON TBO.PRODUCT_ID = TBR.ID;

-- 6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT TBU.BUYER_NAME, TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
WHERE PRODUCT_ID = (
   SELECT ID
   FROM (
      SELECT TBP.ID
      FROM TBL_ORDER TBO
      JOIN TBL_PRODUCT TBP
      ON TBO.PRODUCT_ID = TBP.ID
      JOIN TBL_BUYER TBU
      ON TBO.BUYER_ID = TBU.ID
      GROUP BY TBP.ID, TBP.PRODUCT_BRAND, TBP.PRODUCT_PRICE
      ORDER BY SUM(TBP.PRODUCT_PRICE)
   )
   WHERE ROWNUM = 1
);

--7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
-- 경기도 사람이 구매한 상품 번호

SELECT TBB.*, TBP.PRODUCT_NAME 
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE BUYER_ID IN (
	SELECT ID
	FROM TBL_BUYER
	WHERE BUYER_ADDRESS LIKE '%경기도%'
);


--8) 30대 남성이 가장 많이 구매한 상품의 이름 조회

SELECT PRODUCT_NAME
FROM (
	SELECT PRODUCT_ID ,PRODUCT_NAME, COUNT(PRODUCT_NAME)
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	JOIN TBL_BUYER TBB
	ON TBO.BUYER_ID = TBB.ID
	WHERE TBB.BUYER_AGE >= 30
		AND TBB.BUYER_AGE < 40
		AND TBB.BUYER_GENDER = '남'
	GROUP BY PRODUCT_NAME, PRODUCT_ID 
	ORDER BY COUNT(PRODUCT_NAME) DESC
)
WHERE ROWNUM = 1;


--9) 가장 적게 판매된 상품의 이름

SELECT PRODUCT_NAME
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
FROM(
	SELECT TBO.PRODUCT_ID, COUNT(PRODUCT_ID)
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		GROUP BY TBO.PRODUCT_ID
		ORDER BY COUNT(PRODUCT_ID)
	)
	WHERE ROWNUM <= 2
);


--10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회

SELECT TBP.PRODUCT_NAME, TBB.*
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBO.BUYER_ID IN (
	SELECT ID 
	FROM TBL_BUYER
	WHERE BUYER_AGE > (SELECT AVG(BUYER_AGE) FROM TBL_BUYER) -- 평균 나이 보다 많은 사용자의 ID
);

--11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
SELECT PRODUCT_NAME AS "20대 여성이 구매한 상품", COUNT(PRODUCT_NAME) AS "주문 횟수"
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE 
	BUYER_AGE BETWEEN 20 AND 29
	AND BUYER_GENDER = '여'
GROUP BY PRODUCT_NAME;

--12) 가장 인기가 없는 상품 조회
SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM(
		SELECT PRODUCT_ID, PRODUCT_NAME, COUNT(PRODUCT_NAME)
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		GROUP BY PRODUCT_ID, PRODUCT_NAME
		ORDER BY COUNT(PRODUCT_NAME)
	)
	WHERE ROWNUM <= 2
);

-- 12) 가장 인기가 없는 상품 조회
-- FETCH FIRST(처음부터) ~ 몇 개;
-- FETCH FIRST 2 ROWS ONLY;
SELECT TBP.*
FROM TBL_PRODUCT TBP
JOIN (
   SELECT PRODUCT_ID
   FROM TBL_ORDER
   GROUP BY PRODUCT_ID
   ORDER BY COUNT(PRODUCT_ID) ASC
   FETCH FIRST 2 ROWS ONLY
) TBO
ON TBP.ID = TBO.PRODUCT_ID;

-- OFFSET 행 다음부터 몇 개;
--SELECT COUNT(PRODUCT_ID)
--FROM TBL_ORDER
--GROUP BY PRODUCT_ID
--ORDER BY COUNT(PRODUCT_ID) ASC
--OFFSET 3 ROWS FETCH NEXT 2 ROWS ONLY;




