CREATE TABLE TBL_USER( -- 해당테이블 앞에는 TBL_
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255), -- 변수앞 테이블이름 USER
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR2(255)
);

-- 상품 PRODUCT
-- 상품이름, 상품가격, 상품재고, 상품설명
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255)UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,
	PRODUCT_EXPLANATION VARCHAR2(255)
);



-- SQL언어의 값은 '' 싱글쿼터를 사용한다.
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '이승찬의 맥북', 1500000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램3', 15000);

SELECT * FROM TBL_PRODUCT;
--DROP TABLE TBL_PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;

-- 컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;

-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCHAR2 타입으로 변경
-- 등급 컬럼 삭제

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_GENDER CHAR(5) DEFAULT '남',
	MEMBER_ADDRESS VARCHAR2(255) NOT NULL
);

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '조예성', 27, '경기 군포');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '김정연', 27, '여', '경기 시흥');

SELECT * FROM TBL_MEMBER;

-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCHAR2 타입으로 변경
-- 등급 컬럼 삭제

ALTER TABLE TBL_MEMBER ADD MEMBER_GRADE CHAR(10);

ALTER TABLE TBL_MEMBER MODIFY MEMBER_GRADE VARCHAR2(255);

ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_GRADE;

--DROP TABLE TBL_MEMBER;


CREATE SEQUENCE SEQ_SELF;
CREATE TABLE TBL_SELF(
	ID NUMBER CONSTRAINT PK_SELF PRIMARY KEY,
	SELF_NAME VARCHAR2(255) NOT NULL UNIQUE,
	SELF_MONEY NUMBER DEFAULT 99999,
	SELF_RANK VARCHAR2(255) DEFAULT 'IRON'
);

INSERT INTO TBL_SELF(ID, SELF_NAME, SELF_MONEY)
VALUES(SEQ_SELF.NEXTVAL, '조예성', 105000);

INSERT INTO TBL_SELF(ID, SELF_NAME, SELF_WINNINRATE)
VALUES(SEQ_SELF.NEXTVAL, '조현호', 'GOLD');

SELECT * FROM TBL_SELF;

-- 컬럼 추가
ALTER TABLE TBL_SELF ADD WINNINRATE VARCHAR2(255);

ALTER TABLE TBL_SELF DROP COLUMN WINNINRATE;

-- DB

-- CREATE SEQUENCE SEQ_변수이름;
-- CREATE TABLE TBL_변수이름(
--	ID NUMBER CONSTRAINT PK_변수이름 PRIMARY KEY,
-- 	변수이름_NAME VATCHAR2(255),
--  변수이름_~~ NUMBER UNIQUE NOT NULL 
-- );

-- INSERT INTO TABLE TBL_변수이름(ID, 변수이름_NAME,변수이름_~~)
-- VALUES(SEQ_변수이름.NEXTVAL, '이름', 154);
 
-- ALTER TABLE TBL_변수이름 ADD OR MODIFY OR DROP 변수이름_~~ VALCHAR2(255);





  







