CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR2(255)
);

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'xocds991215', '1234', '조예성', 27, '경기도 군포시');


SELECT * FROM TBL_MEMBER;